---

  - name: add package pre-reqs
    command: apt-get install -y python-apt python-pycurl

  - name: add ola repository
    apt_repository: repo='deb http://apt.openlighting.org/raspbian wheezy main'

  - name: install required packages
    apt: pkg=$item update_cache=yes force=yes
    with_items:
        - ola
        - ola-python
        - python-tornado
        - isc-dhcp-server
        - hostapd

  - name: download hostapd binary for RTl8192cu
    command: wget -q https://www.adafruit.com/downloads/adafruit_hostapd.zip -O /root/adafruit_hostapd.zip creates=/root/adafruit_hostapd.zip

  - name: install hostapd binary
    command: unzip -o /root/adafruit_hostapd.zip hostapd -d /usr/sbin

  - name: make hostapd executable
    file: path=/usr/sbin/hostapd mode=755

  - name: ensure hostapd does not start on boot
    service: name=hostapd enabled=no state=stopped

  - name: ensure isc-dhcp-server does not start on boot
    service: name=isc-dhcp-server enabled=no state=stopped

  - name: configure network interfaces
    template: src=templates/etc/network/interfaces dest=/etc/network/interfaces owner=root group=root

  - name: configure wpa_supplicant
    template: src=templates/etc/wpa_supplicant/wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf owner=root group=root

  - name: configure hostapd
    template: src=templates/etc/hostapd/hostapd.conf dest=/etc/hostapd/hostapd.conf owner=root group=root

  - name: configure hostapd defaults
    template: src=templates/etc/default/hostapd dest=/etc/default/hostapd owner=root group=root

  - name: configure dhcpd
    template: src=templates/etc/dhcp/dhcpd.conf dest=/etc/dhcp/dhcpd.conf owner=root group=root

  - name: configure dhcpd defaults
    template: src=templates/etc/default/isc-dhcp-server dest=/etc/default/isc-dhcp-server owner=root group=root

  - name: install network boot script
    template: src=templates/etc/rc.local dest=/etc/rc.local owner=root group=root mode=755

