---
  - name: recursively copy files over (must run from provisioning folder)
    local_action: command rsync -avzp --rsync-path="sudo rsync" --delete --filter=':- .gitignore' --exclude provisioning --exclude .gitignore --exclude .git -e 'ssh -o "StrictHostKeyChecking no"' ../. pi@${inventory_hostname}:/home/pi/led_head_control
    sudo: no
